language: node_js

node_js:
  # - 12.18.2
  - 14.16.0

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run lint
  - npm test

after_success:
  - npm run coverage

notifications:
  email: false
